name: Feature Request
description: 提交新功能建议
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: 请描述你想要的功能
      render: Markdown
    validations:
      required: true
